const data = [
  { id: "MAT-132", code: "MAT-132", name: "Cálculo I", credits: 5, reqs: [], area: "CB" },
  { id: "MAT-123", code: "MAT-123", name: "Álgebra Lineal", credits: 5, reqs: [], area: "CB" },
  { id: "SIS-111", code: "SIS-111", name: "Introducción a la Programación", credits: 6, reqs: [], area: "SC" },
  { id: "IMT-141", code: "IMT-141", name: "Introducción a la Ing. Mecatrónica", credits: 5, reqs: [], area: "FG" },
  { id: "CAR-109", code: "CAR-109", name: "Escritura Académica", credits: 5, reqs: [], area: "FG" },
  { id: "MAT-133", code: "MAT-133", name: "Cálculo II", credits: 5, reqs: ["MAT-132"], area: "CB" },
  { id: "MAT-142", code: "MAT-142", name: "Probabilidad y Estadística I", credits: 5, reqs: ["MAT-132"], area: "CB" },
  { id: "FIS-111", code: "FIS-111", name: "Física I y Laboratorio", credits: 7, reqs: [], area: "CB" },
  { id: "IMT-121", code: "IMT-121", name: "Circuitos Electrónicos I", credits: 7, reqs: ["MAT-123"], area: "SE" },
  { id: "SIS-112", code: "SIS-112", name: "Programación I", credits: 6, reqs: ["SIS-111"], area: "SC" },
  { id: "MAT-134", code: "MAT-134", name: "Cálculo III", credits: 5, reqs: ["MAT-133"], area: "CB" },
  { id: "FIS-113", code: "FIS-113", name: "Electricidad y Electromagnetismo y Lab", credits: 7, reqs: ["FIS-111"], area: "CB" },
  { id: "FIS-112", code: "FIS-112", name: "Física II y Laboratorio", credits: 7, reqs: ["FIS-111"], area: "CB" },
  { id: "IMT-122", code: "IMT-122", name: "Circuitos Electrónicos II", credits: 7, reqs: ["IMT-121"], area: "SE" },
  { id: "IMT-123", code: "IMT-123", name: "Circuitos Digitales", credits: 7, reqs: ["IMT-121", "SIS-112"], area: "SE" },
  { id: "FHC-140", code: "FHC-140", name: "Formación Humano Cristiana I", credits: 5, reqs: [], area: "FG" },
  { id: "MAT-135", code: "MAT-135", name: "Ecuaciones Diferenciales", credits: 5, reqs: ["MAT-133"], area: "CB" },
  { id: "IMT-211", code: "IMT-211", name: "Mecanismos", credits: 5, reqs: ["MAT-133", "FIS-111"], area: "AC" },
  { id: "IND-202", code: "IND-202", name: "Tecnología Mecánica y Lab", credits: 7, reqs: ["FIS-111"], area: "AC" },
  { id: "IMT-221", code: "IMT-221", name: "Circuitos Electrónicos III", credits: 7, reqs: ["IMT-122"], area: "SE" },
  { id: "IMT-241", code: "IMT-241", name: "Neumática e Hidráulica", credits: 6, reqs: ["FIS-112"], area: "AC" },
  { id: "IMT-242", code: "IMT-242", name: "Máquinas Eléctricas", credits: 6, reqs: ["IMT-121", "FIS-113"], area: "SE" },
  { id: "IMT-212", code: "IMT-212", name: "Diseño de Máquinas", credits: 7, reqs: ["IMT-211", "IND-202"], area: "AC" },
  { id: "IMT-231", code: "IMT-231", name: "Programación Superior", credits: 6, reqs: ["SIS-112"], area: "SC" },
  { id: "IMT-243", code: "IMT-243", name: "Fundamentos de Control", credits: 5, reqs: ["MAT-134", "MAT-135"], area: "AC" },
  { id: "IMT-244", code: "IMT-244", name: "Señales y Sistemas", credits: 6, reqs: ["MAT-142", "MAT-135"], area: "SE" },
  { id: "IND-260", code: "IND-260", name: "Metodología de la Investigación", credits: 5, reqs: ["MAT-142", "CAR-109"], area: "FG" },
  { id: "FHC-240", code: "FHC-240", name: "Formación Humano Cristiana II", credits: 5, reqs: ["FHC-140"], area: "FG" },
  { id: "IMT-222", code: "IMT-222", name: "Sistemas Embebidos I", credits: 6, reqs: ["IMT-123", "IMT-231"], area: "SE" },
  { id: "SIS-341", code: "SIS-341", name: "Sistemas Inteligentes", credits: 6, reqs: ["IMT-231"], area: "SC" },
  { id: "IMT-245", code: "IMT-245", name: "Control I", credits: 6, reqs: ["IMT-243"], area: "AC" },
  { id: "IMT-246", code: "IMT-246", name: "Electrónica de Potencia", credits: 6, reqs: ["IMT-241", "IMT-242", "IMT-221"], area: "SE" },
  { id: "IMT-247", code: "IMT-247", name: "Instrumentación Industrial", credits: 6, reqs: ["IMT-122", "IMT-244"], area: "AC" },
  { id: "IND-330", code: "IND-330", name: "Preparación y Evaluación de Proyectos", credits: 6, reqs: ["IND-260"], area: "FG" },
  { id: "IMT-311", code: "IMT-311", name: "Prototipado Rápido", credits: 6, reqs: ["IMT-212", "IMT-222"], area: "AC" },
  { id: "IMT-312", code: "IMT-312", name: "Manufactura Integrada", credits: 5, reqs: ["IMT-212"], area: "AC" },
  { id: "IMT-322", code: "IMT-322", name: "Sistemas Embebidos II", credits: 6, reqs: ["IMT-222"], area: "SE" },
  { id: "IMT-341", code: "IMT-341", name: "Control II", credits: 6, reqs: ["IMT-245", "IMT-242"], area: "AC" },
  { id: "IMT-344", code: "IMT-344", name: "Visión Artificial", credits: 5, reqs: ["IMT-244", "SIS-341"], area: "SC" },
  { id: "FHC-340", code: "FHC-340", name: "Formación Humano Cristiana III", credits: 5, reqs: ["FHC-240"], area: "FG" },
  { id: "IMT-313", code: "IMT-313", name: "Diseño Superior de Ingeniería", credits: 6, reqs: ["IMT-311", "IMT-312"], area: "AC" },
  { id: "IMT-342", code: "IMT-342", name: "Robótica", credits: 6, reqs: ["IMT-341", "IMT-322"], area: "AC" },
  { id: "IMT-343", code: "IMT-343", name: "Automatización Industrial", credits: 6, reqs: ["IMT-246", "IMT-341", "IMT-247"], area: "AC" },
  { id: "IND-243", code: "IND-243", name: "Seguridad y Salud Ocupacional", credits: 5, reqs: ["IMT-312"], area: "FG" },
  { id: "OPT-1", code: "OPT-1", name: "Optativa I", credits: 5, reqs: ["IND-330"], area: "FG" },
  { id: "IMT-353", code: "IMT-353", name: "Taller de Grado I", credits: 15, reqs: ["IMT-313", "IND-330"], area: "FG" },
  { id: "OPT-2", code: "OPT-2", name: "Optativa II", credits: 5, reqs: ["IND-330"], area: "FG" },
  { id: "IMT-352", code: "IMT-352", name: "Práctica Preprofesional", credits: 5, reqs: ["IMT-343"], area: "FG" },
  { id: "IMT-354", code: "IMT-354", name: "Taller de Grado II", credits: 15, reqs: ["IMT-353" , "IMT-342", "IMT-352" ], area: "FG" },
  ]
